### ISSUE TITLE
도와주세요ㅠㅠ

### ISSUE THREAD

**Issue by DevJuwon** [patrick-mc/optimized-survival#1]
`Error occurred while enabling OptimizedSurvival v1.0-SNAPSHOT (Is it up to date?)
java.nio.file.NoSuchFileException: C:\Users\MakerZip\Desktop\GoormSoft\%23goorm.online\%ec%b5%9c%ec%a0%81%ed%99%94%20%eb%9f%b0\cache\patched_1.16.5.jar`
이런 오류가 떠요

사용 버전
paper 1.16.5 629
각님의 Kotlin-14.32
shadowJar 로 빌드

콘솔로그
```
Patching vanilla jar...
System Info: Java 11 (Java HotSpot(TM) 64-Bit Server VM 11.0.10+8-LTS-162) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[12:51:44 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:51:45 INFO]: Reloading ResourceManager: Default, bukkit
[12:51:46 INFO]: Loaded 7 recipes
[12:51:48 INFO]: Starting minecraft server version 1.16.5
[12:51:48 INFO]: Loading properties
[12:51:48 INFO]: This server is running Paper version git-Paper-629 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[12:51:49 INFO]: Debug logging is disabled
[12:51:49 INFO]: Using 4 threads for Netty based IO
[12:51:49 INFO]: Server Ping Player Sample Count: 12
[12:51:49 INFO]: Default game type: SURVIVAL
[12:51:49 INFO]: Generating keypair
[12:51:49 INFO]: Starting Minecraft server on *:25565
[12:51:49 INFO]: Using default channel type
[12:51:52 INFO]: [Kotlin] Loading Kotlin v1.4.32
[12:51:52 INFO]: [OptimizedSurvival] Loading OptimizedSurvival v1.0-SNAPSHOT
[12:51:52 INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:51:52 INFO]: Preparing level "world"
[12:51:52 INFO]: Preparing start region for dimension minecraft:overworld
[12:51:52 INFO]: Loaded 0 spawn chunks for world world
[12:51:52 INFO]: Preparing spawn area: 0%
[12:51:52 INFO]: Preparing spawn area: 0%
[12:51:52 INFO]: Time elapsed: 577 ms
[12:51:52 INFO]: Preparing start region for dimension minecraft:the_nether
[12:51:53 INFO]: Loaded 0 spawn chunks for world world_nether
[12:51:53 INFO]: Preparing spawn area: 0%
[12:51:53 INFO]: Preparing spawn area: 0%
[12:51:53 INFO]: Time elapsed: 751 ms
[12:51:53 INFO]: Preparing start region for dimension minecraft:the_end
[12:51:53 INFO]: Loaded 0 spawn chunks for world world_the_end
[12:51:53 INFO]: Preparing spawn area: 0%
[12:51:53 INFO]: Time elapsed: 257 ms
[12:51:53 INFO]: [Kotlin] Enabling Kotlin v1.4.32
[12:51:53 INFO]: [OptimizedSurvival] Enabling OptimizedSurvival v1.0-SNAPSHOT
[12:51:54 ERROR]: Error occurred while enabling OptimizedSurvival v1.0-SNAPSHOT (Is it up to date?)
java.nio.file.NoSuchFileException: C:\Users\MakerZip\Desktop\GoormSoft\%23goorm.online\%ec%b5%9c%ec%a0%81%ed%99%94%20%eb%9f%b0\cache\patched_1.16.5.jar
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53) ~[?:?]
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:198) ~[?:?]
        at java.nio.file.Files.readAttributes(Files.java:1764) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1231) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:841) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:247) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:177) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:348) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:319) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:285) ~[?:?]
        at com.github.patrick.survival.optimized.OptimizedSurvivalPlugin.onEnable(OptimizedSurvivalPlugin.kt:75) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[12:51:54 INFO]: [OptimizedSurvival] Disabling OptimizedSurvival v1.0-SNAPSHOT
[12:51:54 INFO]: Running delayed init tasks
[12:51:54 INFO]: Done (5.323s)! For help, type "help"
[12:51:54 INFO]: Timings Reset
> pl
[12:51:59 INFO]: Plugins (2): Kotlin, OptimizedSurvival
>
```

**Comment by patrick-mc** [comment]
?

**Comment by DevJuwon** [comment]
플긴이 로드 안됬다고 떠요..

**Comment by DevJuwon** [comment]
shadowJAR 로 빌드 했네요..ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
distJAR 로 다시 하니까 괜찬아 졌어요! 감사합니다!
